### ISSUE TITLE
Any plans to support null safety?

### ISSUE THREAD

**Issue by talamaska** [DavBfr/flutter_about#13]
Any plans to support null safety?

**Comment by DavBfr** [comment]
Yes, it will be supported as soon as the dependent libraries support it.
Don't hesitate to ping me when it's the case ;)

**Comment by talamaska** [comment]
package_info: ^2.0.0
markdown: ^4.0.0
flutter_markdown: ^0.6.0

were released with nullsafety

**Comment by DavBfr** [comment]
@talamaska yes, the master branch is fully migrated. You can give it a try.

**Comment by talamaska** [comment]
Maybe you forgot to push, cause i don't see a yaml updated with latest deps for nullsafety. This plugin is one of many which I'm waiting to migrate, in order for me to switch.
