### ISSUE TITLE
Desktop bug: Cant load the BuyMe a Coffee image

### ISSUE THREAD

**Issue by gerardwebb** [DavBfr/flutter_about#14]
**Describe the bug**
when running on desktop if the markdown has a link, like "Buy My COffee" in the example, it fails to show the image

The markup it fails on is:

[![Buy Me A Coffee](https://bmc-cdn.nyc3.digitaloceanspaces.com/BMC-button-images/custom_images/orange_img.png "Buy Me A Coffee")](https://www.buymeacoffee.com/JORBmbw9h "Buy Me A Coffee")

The link to the Website https://www.buymeacoffee.com/JORBmbw9h does work 

**To Reproduce**

Just run the example

error is:

````
Another exception was thrown: SocketException: Connection failed (OS Error: Operation not
permitted, errno = 1), address = bmc-cdn.nyc3.digitaloceanspaces.com, port = 443
flutter: Try ./README-en_US.md
flutter: Try ./README-en.md
flutter: Try README.md
flutter: Loaded README.md

Another exception was thrown: SocketException: Connection failed (OS Error: Operation not
permitted, errno = 1), address = bmc-cdn.nyc3.digitaloceanspaces.com, port = 443
````

**Expected behavior**

Show the image.

**Screenshots**
![Screenshot 2021-04-04 at 12 00 03](https://user-images.githubusercontent.com/66615878/113505191-8f9e6c00-953d-11eb-9ceb-5837e43cdea0.png)

**Flutter Doctor**

````
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-DE)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.




**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [ ] Browser
 - [x ] MAC 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by gerardwebb** [comment]
I think it is a Cors related error ?

**Comment by gerardwebb** [comment]
btw  lib/flutter_about.dart fails due to link to Calculator. Had to just blank it out for now.

**Comment by DavBfr** [comment]
To allow your application to open outbound network connections, you have to open the project in XCode, go to capabilities and enable network client.

**Comment by gerardwebb** [comment]
thanks. Know what to do now.

**Comment by gerardwebb** [comment]
You need to add:

<key>com.apple.security.network.client</key>
<true/>
to macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements.
