### ISSUE TITLE
Feature: Load Docs folder and its markdown, so that i can also show User docs.

### ISSUE THREAD

**Issue by gerardwebb** [DavBfr/flutter_about#15]
This code is designed to only load a defined set on markdown and other files, but i was wondering if it could also load a folder called "doc", and then display the markdown in those docs.

Would need to add a tree folder widget too i guess to allow the docs to be nested.

The reason is because i want to include user docs with this package also, and no just dev docs.

I know this package is NOT what this is designed explicitly for, but figured its worth asking about it.

Its very cool but it reflects on the pub spec at build time, etc

**Comment by DavBfr** [comment]
Use a for loop ...

**Comment by gerardwebb** [comment]
GEE THANKS
