### ISSUE TITLE
How do you generate pubspec.dart file

### ISSUE THREAD

**Issue by cloudsbehindthesun** [DavBfr/flutter_about#18]
What command or configuration are you using to generate the pubspec.dart file in the example folder? Are you using https://pub.dev/packages/pubspec_generator for that?

**Comment by david-tangelent** [comment]
how can I make pubspec.dart rebuild on each build? I thought I solved it by adding to pubspec.yaml

builders: 
   pubspec_extract: 

but this doesn't work.
