### ISSUE TITLE
Cannot define scaffoldBuilder for LicenseDetail

### ISSUE THREAD

**Issue by 12people** [DavBfr/flutter_about#19]
**Is your feature request related to a problem? Please describe.**
When using the library's LicenseListPage (or showLicensePage), the ScaffoldBuilder originally passed to the LicenseListPage is not used for the LicenseDetail. There seems to be no way to define the ScaffoldBuilder for the LicenseDetail, short of rewriting the LicenseListPage yourself.

(I'm using the bitsdojo_window package to get a combined app/title bar on Linux and macOS, which makes it imperative that every single Scaffold uses a custom AppBar that allows moving the window and makes room for the window controls. That's why overriding the ScaffoldBuilder is extremely important to me.)

**Describe the solution you'd like**
LicenseDetail should use the same ScaffoldBuilder as the one passed to the LicenseListPage.

**Describe alternatives you've considered**
Alternatively, LicenseListPage could have a property like detailScaffoldBuilder, which would allow defining a separate ScaffoldBuilder for the LicenseDetail page.

**Comment by DavBfr** [comment]
Feel free to implement a solution and fill a PR.

**Comment by 12people** [comment]
Submitted here: #20
