### ISSUE TITLE
Package name of license has many bugs

### ISSUE THREAD

**Issue by liyujiang-gzu** [DavBfr/flutter_about#3]
_fe_analyzer_shared (Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0)    
 flutter_inappwebview (The expected name is 'Flutter InAppWebView', but it is 'Flutter Inappwebview')   
 json_rpc_2(The expected name is 'JSON-RPC 2.0', but it is 'Json Rpc 2')   

Bad code as follows:
```dart
      String packageName = '';
      for (String word in package.split('_')) {
        packageName += word[0].toUpperCase() + word.substring(1) + ' ';
      }
```
Why not use the original package name ?
```dart
      String packageName = package;
      //for (String word in package.split('_')) {
      //  packageName += word[0].toUpperCase() + word.substring(1) + ' ';
      //}
```

**Comment by liyujiang-gzu** [comment]
`asn1lib` has a bug, the subtitle is `http://opensource`, but we except it is `http://opensource.org/licences/BSD-3-Clause`.

Fix code maybe as:
```dart
          String p = license.paragraphs.first.text;
          RegExp reg = new RegExp(p.startsWith('http') ? r' |,|，' : r'\.|。');
          exerpt= p.split(reg).first.trim();
```
![image](https://user-images.githubusercontent.com/16816717/70863719-eae1cf00-1f85-11ea-88a2-935395d53eab.png)

![image](https://user-images.githubusercontent.com/16816717/70863708-c7b71f80-1f85-11ea-9a36-f468116c6819.png)

**Comment by DavBfr** [comment]
Can you create a pull request?
