### ISSUE TITLE
I'm using bottom navbar without top appBar, would like to disable appBar

### ISSUE THREAD

**Issue by agilob** [DavBfr/flutter_about#5]
**Is your feature request related to a problem? Please describe.**
My app doesn't have top appBar, it always uses navbar to navigate and open menus etc. I would like to disable appBar from about page as it's the only widget with appBar.

**Comment by DavBfr** [comment]
Can you create a PR for this?

**Comment by agilob** [comment]
Sorry, but I have to refuse

**Comment by kuhnroyal** [comment]
@DavBfr I have a similar problem, I also need to make changes to the scaffold.
My idea would be to create some sort of `ScaffoldBuilder` as optional parameter to the `AboutPage` which would default to the current behavior if not provided. Would you be open to a PR for this?

**Comment by DavBfr** [comment]
@kuhnroyal you can create a PR, yes!

**Comment by DavBfr** [comment]
Implemented using a ScaffoldBuilder.
