### ISSUE TITLE
Styling the markdownpages

### ISSUE THREAD

**Issue by reinonlein** [DavBfr/flutter_about#9]
Hello, it would be nice if you can add styling to the markdownpages, like padding, textscaling, etc. Is this already possible in the current version, or is this a new feature to be added?

Thanks for the great plugin!

**Comment by DavBfr** [comment]
Yes, it's possible to add this feature. This package uses flutter_markdown for the Markdown rendering. This supports styling:
https://pub.dev/documentation/flutter_markdown/latest/flutter_markdown/Markdown-class.html

Do you want to give it a try and write a PR?

**Comment by reinonlein** [comment]
Hi DavBfr, thanks for your quick reply! I imported another markdownpage using the MarkDownStyleSheet from flutter_markdown and this has the desired effects on that page, but to be honest I have no experience in how to implement this code inside of your plugin. I'm still somewhat of a Flutter-novice in that regard..

To be more precise, I don't know how to connect this piece of code:

`Markdown(
          data: changelog,
          styleSheet:
              MarkdownStyleSheet.fromTheme(Theme.of(context)).copyWith(textScaleFactor: 1.18),
          onTapLink: (url) {
            launch(url);
          },
        ),`

To this:

`child: MarkdownPageListTile(
    filename: changelog,
    title: Text('View Changelog'),
    icon: Icon(Icons.view_list),
          ),`

Do you have a hint, or does this require a lot of work?

**Comment by DavBfr** [comment]
The only way is to pass the parameters all the way down the call tree.

**Comment by reinonlein** [comment]
Okay, i'll give it a try in a next release of my app. Thanks in advance!

**Comment by DavBfr** [comment]
Implemented in version 1.4.0.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
